Initial Commit
ActioFRM/rule-030 pull request #1
Opened 2022-02-10 13:18 UTC by Ayo-lextego

2022-02-14 08:14 UTC, vorsterk requested changes

2022-02-14 08:14 UTC, vorsterk commented on src/controllers/execute.ts
> +    }
Please can you add a return statement , the for (const typology of channel.typologies) to leave the block , It was Foley's Suggested change .

2022-02-14 08:14 UTC, vorsterk commented on src/toMobileNumber.d.ts
> +  toMobileNumber(): string;
Is this needed?

2022-02-14 09:19 UTC, johanfol requested changes

2022-02-15 06:37 UTC, uche-lextego commented on .editorconfig
> +trim_trailing_whitespace = false
ADD end of file line here.

2022-02-15 06:37 UTC, uche-lextego commented on .env.template
> +process.env.CONFIG_COLLECTION=''
Add end of file line here.

2022-02-15 06:37 UTC, uche-lextego commented on .eslintignore
> +*.spec.ts
Add end of file line here

2022-02-15 06:38 UTC, uche-lextego commented on package.json
> +    "fix": "yarn fix:prettier && yarn fix:eslint",
Change everything Yarn on this file to npm run. We don;t use yarn again

2022-02-15 06:40 UTC, uche-lextego requested changes

2022-02-15 06:40 UTC, uche-lextego commented on package.json
> +    "lint": "yarn lint:eslint && yarn lint:prettier",
Here too

2022-02-15 06:40 UTC, uche-lextego commented on rule-030-deploy.yml
> +      - frmpullsecret
End of file line here too

2022-02-15 06:40 UTC, uche-lextego commented on src/toMobileNumber.d.ts
> +  toMobileNumber(): string;
Nope, @Ayo-lextego please remove this file.

2022-02-16 07:56 UTC, johanfol requested changes

2022-02-16 07:56 UTC, johanfol commented on Dockerfile
> +ENV APM_SECRET_TOKEN="eyJhbGciOiJSUzI1NiIsImtpZCI6InRDZTJLUVotZU9ZdXN3cldINktjLTkzVXBNaU1SWHJ1Nm5OR1dNRGM3ck0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC
Please don't commit sensitive information.

2022-02-16 07:56 UTC, johanfol commented on src/controllers/execute.ts
> +          return;
This return is in the wrong location - you're only stopping to send requests to the TP IF there was an issue? That doesn't make sense. Please move this return just one line down (to be inside the oarent IF, but outside the current IF.

2022-02-16 07:56 UTC, johanfol commented on src/services/logic.service.ts
> +  const sRuleConfig = await dbService.getRuleConfig(ruleResult.id);
We should be using id and CFG to get rule config.

2022-02-17 09:52 UTC, vorsterk approved these changes

2022-02-17 10:15 UTC, johanfol requested changes

2022-02-17 10:15 UTC, johanfol commented on src/services/logic.service.ts
> +  for (const messages of req.networkMap.messages) {
Please see comment on Jude's PR, same applies here - just check in with him and Kyle please.

2022-03-01 06:47 UTC, merged